### ISSUE TITLE
I'm trying to add this JS into my Roam via {{[[roam/js]]}} and I get this bug:

### ISSUE THREAD

**Issue by classicrob** [GitMurf/roam-javascript#3]
#object[SyntaxError SyntaxError: Unexpected identifier]

Any thoughts? I know that this has been integrated with Roam toolkit, but I'd love to be able to add it as just standalone JS!

**Comment by djproc** [comment]
i have the same issue…

**Comment by GitMurf** [comment]
Old, closing out. Now filters work natively in Roam.
